### ISSUE TITLE
出現這個錯誤

### ISSUE THREAD

**Issue by billchenbest** [ICE99125/AutoAPI#2]
[Task]
Process completed with exit code 1.
[Task]
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/setup-python@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
[Task]
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by ICE99125** [comment]
nodejs? 这不是 python 嘛

**Comment by billchenbest** [comment]
![image](https://user-images.githubusercontent.com/51526880/231489764-5f0f8db7-e104-421a-a737-50f3c3675d35.png)

**Comment by billchenbest** [comment]
執行兩次都失敗

![image](https://user-images.githubusercontent.com/51526880/231489974-e6625a26-7172-40a7-a157-0d23015f578b.png)

**Comment by billchenbest** [comment]
我也不知道，我只有依照作者的方法去修改

**Comment by ICE99125** [comment]
我这个目前只支持百度云函数和腾讯云函数，不支持 github action

**Comment by billchenbest** [comment]
喔喔，抱歉我好像找錯位置回報問題了

**Comment by billchenbest** [comment]
謝謝回復，打擾了
